### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by bats77** [codeulator/ai-plugin#1]
REQUEST TO CODEULATOR
{
  "liveShareUrl": "https://prod.liveshare.vsengsaas.visualstudio.com/join?7xxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "path": "/",
  "analysisGoal": "understand the project structure"
}
ERROR
An error occurred while executing the plugin.

I apologize for the inconvenience. It seems there's a technical issue preventing me from accessing your VS Code environment. Unfortunately, as an AI, I don't have the capability to provide a detailed log of the error. The error message I receive is generic and doesn't provide specific details about the issue.

-> Whatever I may do or ask for more explanations about this bug, it's stuck at the start (with a projet or with a new project).

**Comment by ghughes** [comment]
Hi, thanks for the report. This should be fixed now. Please try again and let me know.

**Comment by bats77** [comment]
Hi, thanks for your support. It's better but still not efficient ; I tried with two different sessions newly created into 2 different chats - totally repetible (and both I granted read-write access). THanks a lot

***
It seems there's an access issue. When I join your Live Share session, you'll need to initially grant me read-only access. After I've joined, you can then grant me read/write access if needed. 

To do this:

1. Start a new Live Share session.
2. When I request to join, grant me read-only access.
3. Once I've joined, right-click on my bot name in the Live Share explorer and select "Make Read/Write" if you want to grant me write access.

Please provide a new Live Share link once you've done this, and I'll try joining again.
